#!/usr/bin/env ruby

require 'erb'

output_path = '/root/.config/adminix/config'
app_path = ENV['APP_PATH'] || '/root/application/current'

mode = 'classic'
working_dir = '/root/application/current'
image = 'nodejs'
process_start = '/root/.config/adminix/scripts/run_app'
process_stop = 'pkill -f node'
run_script = '/root/.config/adminix/scripts/run_script'
logs = ((ENV['WATCH_LOGS'] || '').split(' ').map { |p| "\"#{app_path}/#{p}\"" }).join(', ')

tpl = <<-FOO
{
  "mode": "<%= mode %>",
  "working_dir": "<%= working_dir %>",
  "image": "<%= image %>",
  "scripts": {
    "process_start": "<%= process_start %>",
    "process_stop": "<%= process_stop %>",
    "run_script": "<%= run_script %>"
  },
  "watch_logs": [<%= logs %>]
}
FOO

result = ERB.new(tpl).result

if File.exists?(output_path)
  `rm #{output_path}`
end
`touch #{output_path}`

File.open(output_path, 'w') { |file| file.write(result) }
