#!/bin/bash

echo "Syncing remote variables..."
eval $(/usr/local/rvm/gems/ruby-2.5.1@adminix/wrappers/adminix env)
echo "ok"

echo "Changing application folder..."
cd $APP_PATH
echo "ok"

echo "Connecting Ruby..."
source "/usr/local/rvm/scripts/rvm"
rvm gemset use default
echo "ok"

echo "Connecting Node.js..."
source $NVM_DIR/nvm.sh
echo "ok"

echo "Executing script..."
$@
echo "ok"
