#!/bin/bash

function update_adminix() {
  rvm gemset use ruby-2.5.1@adminix
  gem install adminix
}

function run () {
  eval $(/usr/local/rvm/gems/ruby-2.5.1@adminix/wrappers/adminix env)
  
  git clone $GIT_REPO /tmp/repo
  rm -rf $APP_PATH/*
  yes | cp -a /tmp/repo/. $APP_PATH
  rm -rf /tmp/repo

  cd $APP_PATH

  rm /tmp/adminix.pid
  /usr/local/rvm/gems/ruby-2.5.1@adminix/wrappers/adminix watch --daemonize
 
  file=run.sh
  if [ -f "$file" ]
  then
    chmod a+x adminix_run.sh
    ./adminix_run.sh
  else
    gem install tzinfo-data
    bundle install
    bundle exec rake assets:precompile
    exec bundle exec rails server -b 0.0.0.0
  fi
}

ACTION="${1:-start}"

if [ "$ACTION" = "start" ]; then
  echo "Running application..."
  source "/usr/local/rvm/scripts/rvm"
  source $NVM_DIR/nvm.sh

  update_adminix
  run
else
  echo "Running command"
  exec "$@"
fi
