#!/bin/bash

echo "Cloning Git repository..."
rm -rf $TMP_PATH
git clone $GIT_REPO -b $GIT_BRANCH $TMP_PATH
echo "OK"
echo "$Changing project folder..."
cd $TMP_PATH
echo "OK"

echo "Connecting Ruby and Node.js..."
source "/usr/local/rvm/scripts/rvm"
rvm gemset use default
source $NVM_DIR/nvm.sh
echo "OK"

echo "Preparing app..."
bundle install
if [ -f "package.json" ]; then
    yarn install
fi
bundle exec rake assets:precompile
echo "OK"

echo "Updating folders..."
yes | cp -a $APP_PATH $LEGACY_PATH
rm -rf $APP_PATH/*
yes | cp -a $TMP_PATH $APP_PATH
rm -rf $TMP_PATH
echo "OK"

echo "Launching app..."
exec bundle exec rails server -b 0.0.0.0 -p $PORT
echo "OK"
