#!/bin/bash

function run_app() {

  echo "Cloning Git repository..."
  rm -rf $TMP_PATH
  git clone $GIT_REPO -b $GIT_BRANCH $TMP_PATH
  echo "OK"
  echo "Changing project folder..."
  cd $TMP_PATH
  echo "OK"

  echo "Connecting Ruby and Node.js..."
  source "/usr/local/rvm/scripts/rvm"
  source $NVM_DIR/nvm.sh
  echo "OK"

  echo "Preparing app..."
  bundle install
  if [ -f "package.json" ]; then
    yarn install
  fi
  bundle exec rake assets:precompile
  echo "OK"

  echo "Updating folders..."
  rm -rf $LEGACY_PATH
  mv $APP_PATH $LEGACY_PATH
  rm -rf $APP_PATH
  mv $TMP_PATH $APP_PATH
  rm -rf $TMP_PATH
  echo "OK"

  echo "Changing folder..."
  cd $APP_PATH
  echo "OK"

  exec bundle exec rails server -b 0.0.0.0 -p $PORT
}

function run_script() {
  cd $APP_PATH
  source "/usr/local/rvm/scripts/rvm"
  source $NVM_DIR/nvm.sh
  exec "$@"
}

echo "Launching app..."
ACTION="${1:-start}"

if [ "$ACTION" = "start" ]; then
  run_app
else
  echo "Running command"
  run_script
fi
