#!/bin/bash

echo "Cloning Git repository..."
git clone $GIT_REPO -b $GIT_BRANCH /tmp/repo
rm -rf $APP_PATH/*
yes | cp -a /tmp/repo/. $APP_PATH
rm -rf /tmp/repo
echo "OK"

echo "$Changing project folder..."
cd $APP_PATH
echo "OK"

echo "Connecting Ruby and Node.js..."
source "/usr/local/rvm/scripts/rvm"
rvm gemset use default
source $NVM_DIR/nvm.sh
echo "OK"

echo "Launching app..."
file=run.sh
if [ -f "$file" ]
then
    chmod a+x adminix_run.sh
    ./adminix_run.sh
else
    bundle install
    if [ -f "package.json" ]; then
	yarn install
    fi
    bundle exec rake assets:precompile
    exec bundle exec rails server -b 0.0.0.0
fi
